name: build
on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  image:
    strategy:
      fail-fast: false
      matrix:
        release: [focal, jammy]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name=quay.io/vexxhost/openstack-builder-${{ matrix.release }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD'}}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
          tags: ${{ steps.meta.outputs.tags }}
          platforms: |
            linux/amd64
            linux/arm64
